port: 8080


spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    name: MySQL Connection
    url: jdbc:mysql://localhost:3306/learning_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true

custom-auth:
  key: aabbcc4567

fs:
  base-Url : \Users\Korisnik\Desktop\LearningStation\uis\src\main\resources\Files\
  front-Url : \Users\Korisnik\Desktop\LearningStation\uis\src\main\resources\Files\